workflows:
  android-build:
    name: Build Android Debug APK
    max_build_duration: 120
    environment:
      vars:
        PACKAGE_NAME: "com.miningapp"
        GRADLE_JVM_ARGS: "-Xmx2g" # Noch weiter runter
    scripts:
      - name: Set gradlew Permissions
        script: |
          chmod +x gradlew
      - name: Stop Gradle Daemon
        script: |
            ./gradlew --stop
    artifacts:
      - app/build/outputs/apk/debug/*.apk
