workflows:
  android-build:
    name: Build Android Debug APK
    max_build_duration: 120
    environment:
      vars:
        PACKAGE_NAME: "com.miningapp"
        GRADLE_JVM_ARGS: "-Xmx6g"
    scripts:
      # ... (deine Build-Skripte) ...
    artifacts:
      - app/build/outputs/apk/debug/*.apk
