#!/usr/bin/env bash

# Überprüfen, ob Java 17 bereits installiert ist
if java -version 2>&1 | grep -q "17."; then
  echo "Java 17 ist bereits installiert."
else
  echo "Java 17 ist nicht installiert. Versuche Installation."
  #Versuche die Installation von OpenJDK 17
  if command -v apt-get &> /dev/null; then
    sudo apt-get update
    sudo apt-get install -y openjdk-17-jdk
  elif command -v apk &> /dev/null; then
    sudo apk update
    sudo apk add openjdk17-jdk
  elif command -v yum &> /dev/null; then
    sudo yum install -y java-17-openjdk-devel
  elif command -v dnf &> /dev/null; then
    sudo dnf install -y java-17-openjdk-devel
  else
    echo "Paketmanager nicht gefunden. Java muss manuell installiert werden."
    exit 1
  fi

  # Überprüfen, ob die Installation erfolgreich war
  if ! java -version 2>&1 | grep -q "17."; then
    echo "Fehler bei der Installation von Java 17."
    exit 1
  fi
  echo "Java 17 erfolgreich installiert"
fi
# Ausgabe der Java Version
java -version
