workflows:
  android-build:
    name: Build APK
    max_build_duration: 60
    instance_workflows:
  android-build:
    name: Build APK
    max_build_duration: 60
    instance_type: linux_x2  # Mehr RAM für Codemagic
    environment:
      android_signing:
        credentials:
          release: release-key
      vars:
        PACKAGE_NAME: "com.miningapp"
    scripts:
      - name: Install Java (Falls nicht vorhanden)
        script: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk

      - name: Set Gradle permissions
        script: |
          chmod +x gradlew
          chmod +x gradle/wrapper/gradle-wrapper.jar

      - name: Build Debug APK
        script: |
          export GRADLE_OPTS="-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=-Xmx512m"
          ./gradlew assembleDebug --no-daemon --stacktrace

    artifacts:
      - app/build/outputs/*/.apktype: linux_x2  # Mehr RAM für Codemagic
    environment:
      vars:
        PACKAGE_NAME: "com.miningapp"
    scripts:
      - name: Install Java (Falls nicht vorhanden)
        script: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk

      - name: Set Gradle permissions
        script: |
          chmod +x gradlew
          chmod +x gradle/wrapper/gradle-wrapper.jar

      - name: Build Debug APK
        script: |
          export GRADLE_OPTS="-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=-Xmx512m"
          ./gradlew assembleDebug --no-daemon --stacktrace

    artifacts:
      - app/build/outputs/*/.apk
