workflows:
  android-build:
    name: Build APK
    max_build_duration: 60
    instance_type: linux_x2  # Nutze eine stabile Linux-Instanz
    environment:
      android_signing:
      vars:
        PACKAGE_NAME: "com.miningapp"
    scripts:
      - name: Install Java (Falls nicht vorhanden)
        script: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk

      - name: Set Gradle permissions
        script: |
          chmod +x gradlew

      - name: Clean Project
        script: |
          ./gradlew clean

      - name: Build Debug APK
        script: |
          ./gradlew assembleDebug --no-daemon

    artifacts:
      - app/build/outputs/*/.apk
