workflows:
  android-build:
    name: Build APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - release-key
    scripts:
      - name: Set Gradle permissions
        script: |
          chmod +x gradlew
      - name: Build Debug APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/*/.apk
