workflows:
  android-build:
    name: Build APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - keystore_reference
      groups:
        - google_credentials
      vars:
        PACKAGE_NAME: "com.miningapp"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
          source: true
    scripts:
      - name: Set up JDK
        script: |
          echo "Setting up JDK 17"
          java -version
      - name: Build Debug APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/*/.apk
