workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 120
    environment:
      flutter: stable
      vars:
        PACKAGE_NAME: "com.example.myapp" # Ersetze mit deinem Paketnamen
      groups:
        - google_credentials # Stelle sicher, dass diese Env-Var existiert

    scripts:
      - echo "📦 Running Flutter Clean"
      - flutter clean
      - echo "📦 Running Flutter Pub Get"
      - flutter pub get
      - echo "🔧 Building APK"
      - flutter build apk --release

    artifacts:
      - build/*/outputs//.apk # Stellt sicher, dass das APK gespeichert wird

    publishing:
      email:
        recipients:
          - deine-email@example.com  # Ersetze mit deiner E-Mail
      android:
        artifacts:
          - app-release.apk
        signing:
          credentials: $CM_KEYSTORE_PATH
          keystore_password: $CM_KEYSTORE_PASSWORD
          key_alias: $CM_KEY_ALIAS
          key_password: $CM_KEY_PASSWORD
