workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 120
    environment:
      flutter: stable
      vars:
        PACKAGE_NAME: "com.example.myapp" # Ersetze mit deinem Paketnamen
      groups:
        - google_credentials # Stelle sicher, dass diese Env-Var existiert

    working_directory: app  # <<< Sorgt dafür, dass alle Befehle im "app"-Ordner laufen

    scripts:
      - echo "📦 Checking if pubspec.yaml exists"
      - if [ ! -f "pubspec.yaml" ]; then echo "❌ ERROR: pubspec.yaml not found!"; exit 1; fi
      - echo "📦 Running Flutter Clean"
      - flutter clean
      - echo "📦 Running Flutter Pub Get"
      - flutter pub get
      - echo "🔧 Building APK"
      - flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk  # Exakter Pfad zur APK-Datei

    publishing:
      android:
        artifacts:
          - app-release.apk
        signing:
          credentials: $CM_KEYSTORE_PATH
          keystore_password: $CM_KEYSTORE_PASSWORD
          key_alias: $CM_KEY_ALIAS
          key_password: $CM_KEY_PASSWORD
